### ISSUE TITLE
Netflix Conductor repository moved Postgres modules to the community-repository

### ISSUE THREAD

**Issue by jhonnyman** [erikbrgr/conductor-es7-postgres#3]
[Question]

Hello Eric,

I found your guide very helpful. Finally I was able to make Conductor use Postgres database.
My use case is we want to use Conductor to orchestrate long running workflows (in months) so having Postgres persistence is key for moving forward with Conductor.

Recently Netflix moved Postgres modules from the main repository to a new conductor-community repository.
How do you approach this change?

**Comment by erikbrgr** [comment]
Hi @jhonnyman! I haven't looked at the implications of the new repo structure, although if all they did was move code, it should be fairly trivial to come up with a script that pulls the required postgres folders and puts them wherever they should go. 
As soon as I have some time (not soon, I'm afraid), I'll investigate further and document my findings here or in a new article. 
Sorry I cannot be of more help at the moment. 
Best, Erik

**Comment by jhonnyman** [comment]
Thank you Erik. I though of that as well but as I'm still learning the ins and outs of Conductor did not try it so far.

By the way, have you used Conductor for modelling long running transactions with persistence?

**Comment by erikbrgr** [comment]
We used Conductor for ETL processes through a .NET worker, which could easily take several hours. If that's what you mean, then yes I did 🙂

**Comment by jhonnyman** [comment]
That's great. Actually I intend to use Conductor to orchestrate business logic in our main application.
It makes modelling workflows easy.
I'm also evaluating if we could store the process information inside the workflow, avoiding different databases.

From what I understand so far, Conductor recomends the payload to be less than 100kb.
But as we deal with lots of files, the best approach would be to persist the workflow payload in something like AWS S3 and dinamically read and write it.

Do you think this would be a good fit? Or do you see any road blocks for such a use case?
Thank you

**Comment by erikbrgr** [comment]
This would be a great fit. A different group at my project used S3, and I used the local (Linux) filesystem to deal with huge files. So that would definitely work.

On 28 Jul 2022, at 15:07, jhonnyman ***@***.***> wrote:

﻿

That's great. Actually I intend to use Conductor to orchestrate business logic in our main application.
It makes modelling workflows easy.
I'm also evaluating if we could store the process information inside the workflow, avoiding different databases.

From what I understand so far, Conductor recomends the payload to be less than 100kb.
But as we deal with lots of files, the best approach would be to persist the workflow payload in something like AWS S3 and dinamically read and write it.

Do you think this would be a good fit? Or do you see any road blocks for such a use case?
Thank you

**Comment by jhonnyman** [comment]
Thank you Erik! I'm sure we will making a good decision moving forward with Conductor
